// Generated by generate.mjs. Do not edit by hand.
(() => {
  const deepFreeze = (value) => {
    if (value && typeof value === "object" && !Object.isFrozen(value)) {
      Object.freeze(value);
      Object.values(value).forEach(deepFreeze);
    }
    return value;
  };

  window.LTL_G2_PRECISION_REVIEW = deepFreeze({
  "dataset": {
    "campaignReportIdentity": "sha256:4bf9ed002f7c75f0df4bfc5e7b4ecf22f810cefed148afb273ae616f7500d00f",
    "claimBoundary": "Checker counterexamples; pending reviewer validation. No user-impact or effectiveness claim.",
    "id": "g2-formal-4bf9ed002f7c75f0",
    "identity": "sha256:587e8ab8d5e1dbee38b2e8178187edf9b3e1a58acbc8971eb3597b0fb3d29307",
    "producerSourceCommit": "1bba7afd98e2d198911c2bdf48ea4213d2c3eaca",
    "title": "G2 checker counterexamples",
    "verifierSourceCommit": "6ec301d82ab4c86ad9829681b3b4721b673537af"
  },
  "findings": [
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "004__airbnb__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "004__airbnb__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/004__airbnb__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:ba1dc256bb1796e31f5045316fa7d05af3d70bf22e9d0ab85f5757d3a5fd2637"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::004__airbnb__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 1,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "airbnb",
      "slug": "formal-1-airbnb-ap-fm1-01-254a445124ca",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "airbnb"
            },
            {
              "label": "Control",
              "value": "Done"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/581ec04a9c4245ff145a7060455c44c82d4904a4d684a95d49cf97f1662758c6.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:581ec04a9c4245ff145a7060455c44c82d4904a4d684a95d49cf97f1662758c6",
          "label": "Counterexample",
          "state": "Done · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Done · VIOLATION_OBSERVED",
      "title": "airbnb · AP-FM1-01"
    },
    {
      "atomicId": "AP-W3-01",
      "attemptId": "004__airbnb__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "004__airbnb__g2-taxonomy-informed__120s__replay-1:AP-W3-01:first-counterexample",
        "resultPath": "evidence/results/004__airbnb__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:ba1dc256bb1796e31f5045316fa7d05af3d70bf22e9d0ab85f5757d3a5fd2637"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::004__airbnb__g2-taxonomy-informed__120s__replay-1:AP-W3-01:first-counterexample",
      "order": 2,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "airbnb",
      "slug": "formal-2-airbnb-ap-w3-01-46450bf16a90",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "airbnb"
            },
            {
              "label": "Control",
              "value": "Save The Seashell House to wishlist"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/f1447adabb02416644860c958af4ead03ab99bba620821e839435d353a8e4fa8.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:f1447adabb02416644860c958af4ead03ab99bba620821e839435d353a8e4fa8",
          "label": "Counterexample",
          "state": "Save The Seashell House to wishlist · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Save The Seashell House to wishlist · VIOLATION_OBSERVED",
      "title": "airbnb · AP-W3-01"
    },
    {
      "atomicId": "AP-M1-05",
      "attemptId": "010__apartments__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "010__apartments__g2-taxonomy-informed__120s__replay-1:AP-M1-05:first-counterexample",
        "resultPath": "evidence/results/010__apartments__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:b040802b01d963bfe3817de40bfa21b642af2d301dd16cde9f9e148130d76f96"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::010__apartments__g2-taxonomy-informed__120s__replay-1:AP-M1-05:first-counterexample",
      "order": 3,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "apartments",
      "slug": "formal-3-apartments-ap-m1-05-1148db648752",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "apartments"
            },
            {
              "label": "Control",
              "value": "new modal opener"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/4eafbaf3bf2b82c90f52dbb255d9d6a262e95406da12a4ab63f7d602fd144f5b.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:4eafbaf3bf2b82c90f52dbb255d9d6a262e95406da12a4ab63f7d602fd144f5b",
          "label": "Counterexample",
          "state": "new modal opener · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · new modal opener · VIOLATION_OBSERVED",
      "title": "apartments · AP-M1-05"
    },
    {
      "atomicId": "AP-M1-03",
      "attemptId": "012__babycenter__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "012__babycenter__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
        "resultPath": "evidence/results/012__babycenter__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:6f34ae5b1b215f605270f6a7091d2cf0e2d22fe67f458890b356ebb48d02b0aa"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::012__babycenter__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
      "order": 4,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "babycenter",
      "slug": "formal-4-babycenter-ap-m1-03-98cc95495953",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "babycenter"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/20491cac891c7a74b5dabbaabc8562e1244ae72129b45a9ce8f36035c3da23f1.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:20491cac891c7a74b5dabbaabc8562e1244ae72129b45a9ce8f36035c3da23f1",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "babycenter · AP-M1-03"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "019__ca-gov__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "019__ca-gov__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/019__ca-gov__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:11191dafced05126779a8c76f5ca913c646713f5770b5f74e6cfb6ed567f998c"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::019__ca-gov__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 5,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "ca-gov",
      "slug": "formal-5-ca-gov-ap-fm1-01-1e3068afa91b",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "ca-gov"
            },
            {
              "label": "Control",
              "value": "Start application"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/e075788507bffb3f646a1e9dc846a7acd3f62526f2cdd308d53b818199e7afbd.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:e075788507bffb3f646a1e9dc846a7acd3f62526f2cdd308d53b818199e7afbd",
          "label": "Counterexample",
          "state": "Start application · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Start application · VIOLATION_OBSERVED",
      "title": "ca-gov · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-03",
      "attemptId": "023__carmax__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "023__carmax__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
        "resultPath": "evidence/results/023__carmax__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:4365deeb30a83b593f2c960f7f59920e89ce00717deed4e0acb8a79dbd1a9f95"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::023__carmax__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
      "order": 6,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "carmax",
      "slug": "formal-6-carmax-ap-m1-03-d78a873727d4",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "carmax"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/e8c36361e2dc19808ae14c759a12c52075a76c52d5df9f853c3cd56299e0d89b.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:e8c36361e2dc19808ae14c759a12c52075a76c52d5df9f853c3cd56299e0d89b",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "carmax · AP-M1-03"
    },
    {
      "atomicId": "AP-M1-04",
      "attemptId": "026__coinmarketcap__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "026__coinmarketcap__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
        "resultPath": "evidence/results/026__coinmarketcap__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:bda7256c9a4e83e70a115dc51f3e6c11aab90d19909477fd487d1f20af5f000d"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::026__coinmarketcap__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
      "order": 7,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "coinmarketcap",
      "slug": "formal-7-coinmarketcap-ap-m1-04-bf6c5975fced",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "coinmarketcap"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/e5d8188d63e0d0f308d86276e63b4183db4265ac55761350b55d097a3e71e477.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:e5d8188d63e0d0f308d86276e63b4183db4265ac55761350b55d097a3e71e477",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "coinmarketcap · AP-M1-04"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "037__epicurious__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "037__epicurious__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/037__epicurious__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:705bc7a0021f341f6ade415ecd957e6a228de6127abc4af0dd91e672635889e9"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::037__epicurious__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 8,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "epicurious",
      "slug": "formal-8-epicurious-ap-fm1-01-0dbea3a048ef",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "epicurious"
            },
            {
              "label": "Control",
              "value": "Remove Rice & Millet Skillet Bread from favorites"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/bc54a4634473ccb5e30cfae92ab7ea6dd3e50d2f35dcc193c8e970293096e888.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:bc54a4634473ccb5e30cfae92ab7ea6dd3e50d2f35dcc193c8e970293096e888",
          "label": "Counterexample",
          "state": "Remove Rice & Millet Skillet Bread from favorites · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Remove Rice & Millet Skillet Bread from favorites · VIOLATION_OBSERVED",
      "title": "epicurious · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "041__exploretock__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "041__exploretock__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/041__exploretock__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:b7da3e6bc98a04465aefcb3efd1628fb3e9e7a0c69992e7cedb23eeb99f177b9"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::041__exploretock__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 9,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "exploretock",
      "slug": "formal-9-exploretock-ap-fm1-01-58756cc45007",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "exploretock"
            },
            {
              "label": "Control",
              "value": "Reserve now"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/d9305f2175af4033710150896ae58f9a59774e3ef2893e5758b0e8ae5949e2cf.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:d9305f2175af4033710150896ae58f9a59774e3ef2893e5758b0e8ae5949e2cf",
          "label": "Counterexample",
          "state": "Reserve now · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Reserve now · VIOLATION_OBSERVED",
      "title": "exploretock · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-04",
      "attemptId": "044__finance-google__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "044__finance-google__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
        "resultPath": "evidence/results/044__finance-google__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:9d682d3d1b74d97bf60a15034f4a551f7d33c898b448faf522e3a5bacd0fffff"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::044__finance-google__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
      "order": 10,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "finance-google",
      "slug": "formal-10-finance-google-ap-m1-04-b075aeba384f",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "finance-google"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/014d171591452483d46852bd99d04bd10b6ed7da85992feaadfbdfe78c11aee0.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:014d171591452483d46852bd99d04bd10b6ed7da85992feaadfbdfe78c11aee0",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "finance-google · AP-M1-04"
    },
    {
      "atomicId": "AP-M1-04",
      "attemptId": "051__health-usnews__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "051__health-usnews__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
        "resultPath": "evidence/results/051__health-usnews__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:dddeacec5bf2b6c42a2d4a7296a5d3b400e3cb2b162cede8ab408faaa6f562c8"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::051__health-usnews__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
      "order": 11,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "health-usnews",
      "slug": "formal-11-health-usnews-ap-m1-04-01611866afc2",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "health-usnews"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/dda4f9e38cd204c5606fbf3ed92d05581b9c538756c857420de0093e6c575948.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:dda4f9e38cd204c5606fbf3ed92d05581b9c538756c857420de0093e6c575948",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "health-usnews · AP-M1-04"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "054__hiring-amazon__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "054__hiring-amazon__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/054__hiring-amazon__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:881f9f9672d8e9af79a4acc0ad6f89d3f02c0fbace3fd0cc331e0f1e511b573d"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::054__hiring-amazon__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 12,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "hiring-amazon",
      "slug": "formal-12-hiring-amazon-ap-fm1-01-aef02c906cc4",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "hiring-amazon"
            },
            {
              "label": "Control",
              "value": "Sign up for alerts"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/3b946638cdf68d02fce06fb3715a435f3d196ec1e42909b256538b1a21538a69.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:3b946638cdf68d02fce06fb3715a435f3d196ec1e42909b256538b1a21538a69",
          "label": "Counterexample",
          "state": "Sign up for alerts · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Sign up for alerts · VIOLATION_OBSERVED",
      "title": "hiring-amazon · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "055__ign__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "055__ign__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/055__ign__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:4935c30a118b7a709999939b30ff8390dae03527cba5c926a21f59d764601fc5"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::055__ign__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 13,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "ign",
      "slug": "formal-13-ign-ap-fm1-01-2c090cbe9f45",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "ign"
            },
            {
              "label": "Control",
              "value": "Save story"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/2ad48a0cc31d681f5d6074fa2c0ffac94c3b163a003bb310a35c41dec877df41.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:2ad48a0cc31d681f5d6074fa2c0ffac94c3b163a003bb310a35c41dec877df41",
          "label": "Counterexample",
          "state": "Save story · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Save story · VIOLATION_OBSERVED",
      "title": "ign · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "063__kbb__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "063__kbb__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/063__kbb__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:b8341d82e4046e5cbac91af5d577cffc2547442fa366a01b7f1eadd4679b69ca"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::063__kbb__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 14,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "kbb",
      "slug": "formal-14-kbb-ap-fm1-01-14a3216ed910",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "kbb"
            },
            {
              "label": "Control",
              "value": "Continue"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/2f29a0003cb5646f61364c3cf5f41dd3a734c74f51f77b78033cb419cc6c9fdb.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:2f29a0003cb5646f61364c3cf5f41dd3a734c74f51f77b78033cb419cc6c9fdb",
          "label": "Counterexample",
          "state": "Continue · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Continue · VIOLATION_OBSERVED",
      "title": "kbb · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-03",
      "attemptId": "063__kbb__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "063__kbb__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
        "resultPath": "evidence/results/063__kbb__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:b8341d82e4046e5cbac91af5d577cffc2547442fa366a01b7f1eadd4679b69ca"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::063__kbb__g2-taxonomy-informed__120s__replay-1:AP-M1-03:first-counterexample",
      "order": 15,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "kbb",
      "slug": "formal-15-kbb-ap-m1-03-215bc9deb269",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "kbb"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/ff7dee88abd70f06d7cc099059aa3e4d2f7f906cb6d4214651528fc2ad1db07f.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:ff7dee88abd70f06d7cc099059aa3e4d2f7f906cb6d4214651528fc2ad1db07f",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "kbb · AP-M1-03"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "065__kohls__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "065__kohls__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/065__kohls__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:42be776aaa686b573e14d83599f933469b4ab994bce5611bf87ff6c031b9ae91"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::065__kohls__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 16,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "kohls",
      "slug": "formal-16-kohls-ap-fm1-01-47b6c47b2b14",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "kohls"
            },
            {
              "label": "Control",
              "value": "Clear filters"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/f0aea8a977274ad402014d16c78236fff584a585f76193a40ac5955d9cf442e8.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:f0aea8a977274ad402014d16c78236fff584a585f76193a40ac5955d9cf442e8",
          "label": "Counterexample",
          "state": "Clear filters · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Clear filters · VIOLATION_OBSERVED",
      "title": "kohls · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-05",
      "attemptId": "074__movoto__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "074__movoto__g2-taxonomy-informed__120s__replay-1:AP-M1-05:first-counterexample",
        "resultPath": "evidence/results/074__movoto__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:2c472b9be84b6928f52d79bcb1799c21c5772866576c2fedb38b4fc29b8a7da1"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::074__movoto__g2-taxonomy-informed__120s__replay-1:AP-M1-05:first-counterexample",
      "order": 17,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "movoto",
      "slug": "formal-17-movoto-ap-m1-05-ad21d7b75236",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "movoto"
            },
            {
              "label": "Control",
              "value": "new modal opener"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/4621168c6549a2a82213b16f8b56d34a265febc257834a14ac5f03c5cc020753.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:4621168c6549a2a82213b16f8b56d34a265febc257834a14ac5f03c5cc020753",
          "label": "Counterexample",
          "state": "new modal opener · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · new modal opener · VIOLATION_OBSERVED",
      "title": "movoto · AP-M1-05"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "078__nfl__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "078__nfl__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/078__nfl__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:955c8d1469ba985a6d4fffc18d28f75247f5df1f93736e29597f294e278eea91"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::078__nfl__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 18,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "nfl",
      "slug": "formal-18-nfl-ap-fm1-01-b2e99098d09b",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "nfl"
            },
            {
              "label": "Control",
              "value": "Show 49ers schedule"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/3e98d02b31baf866256b76188852abfed0e406e0aabd93e5353829122e75d1b1.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:3e98d02b31baf866256b76188852abfed0e406e0aabd93e5353829122e75d1b1",
          "label": "Counterexample",
          "state": "Show 49ers schedule · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Show 49ers schedule · VIOLATION_OBSERVED",
      "title": "nfl · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "099__shopping-google__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "099__shopping-google__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/099__shopping-google__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:cec73c986b0590b103c7764ef350c6eba5d588246ba29d8d088125677f322129"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::099__shopping-google__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 19,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "shopping-google",
      "slug": "formal-19-shopping-google-ap-fm1-01-3714bb848a1d",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "shopping-google"
            },
            {
              "label": "Control",
              "value": "4"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/401c9821de0c4a3a9aa3c407d8cc74fd6c9137241ec55cedd7d181f3e17d88aa.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:401c9821de0c4a3a9aa3c407d8cc74fd6c9137241ec55cedd7d181f3e17d88aa",
          "label": "Counterexample",
          "state": "4 · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · 4 · VIOLATION_OBSERVED",
      "title": "shopping-google · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "102__sports-yahoo__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "102__sports-yahoo__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/102__sports-yahoo__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:5baa0f1d6c992de9ffb33273383f874f3f20e3469e782e06f268c8aff3a3f2bb"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::102__sports-yahoo__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 20,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "sports-yahoo",
      "slug": "formal-20-sports-yahoo-ap-fm1-01-d4e6f3cde02d",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "sports-yahoo"
            },
            {
              "label": "Control",
              "value": "Remove LeBron James injury update: Lakers star progressing after foot issue"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/ce099796f7809dc6e71a98c9c29c1ac529e2cdb1086fb5e19676b74757a0ce17.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:ce099796f7809dc6e71a98c9c29c1ac529e2cdb1086fb5e19676b74757a0ce17",
          "label": "Counterexample",
          "state": "Remove LeBron James injury update: Lakers star progressing after foot issue · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Remove LeBron James injury update: Lakers star progressing after foot issue · VIOLATION_OBSERVED",
      "title": "sports-yahoo · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-04",
      "attemptId": "102__sports-yahoo__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "102__sports-yahoo__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
        "resultPath": "evidence/results/102__sports-yahoo__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:5baa0f1d6c992de9ffb33273383f874f3f20e3469e782e06f268c8aff3a3f2bb"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::102__sports-yahoo__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
      "order": 21,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "sports-yahoo",
      "slug": "formal-21-sports-yahoo-ap-m1-04-38c21f3d9b21",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "sports-yahoo"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/f767d500410f5d799146c67f0c027e2989a81891460aa83de070b6e58c1ad870.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:f767d500410f5d799146c67f0c027e2989a81891460aa83de070b6e58c1ad870",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "sports-yahoo · AP-M1-04"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "104__stocktwits__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "104__stocktwits__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/104__stocktwits__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:5b6bf985d66fa4e58a058f6971e9280a6849b1cc69bb437f69a0f18f42d9e81c"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::104__stocktwits__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 22,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "stocktwits",
      "slug": "formal-22-stocktwits-ap-fm1-01-85c43c3c59fc",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "stocktwits"
            },
            {
              "label": "Control",
              "value": "Cancel"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/7a1428ccfac91ef7cb76767d28b051657c92c614f32792f00c57d6b17c9c19f0.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:7a1428ccfac91ef7cb76767d28b051657c92c614f32792f00c57d6b17c9c19f0",
          "label": "Counterexample",
          "state": "Cancel · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Cancel · VIOLATION_OBSERVED",
      "title": "stocktwits · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "114__tiktok-music__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "114__tiktok-music__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/114__tiktok-music__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:79159b90ea8b8d905692a8b9e48bfdf43192ee6b1392d805072b72d36bafb294"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::114__tiktok-music__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 23,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "tiktok-music",
      "slug": "formal-23-tiktok-music-ap-fm1-01-324cb2884ec0",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "tiktok-music"
            },
            {
              "label": "Control",
              "value": "Close NovaBook Air 14 performance"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/7fc1623bc26f502e08086029ed04750ec5806c45087cd1592030a153d61f050b.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:7fc1623bc26f502e08086029ed04750ec5806c45087cd1592030a153d61f050b",
          "label": "Counterexample",
          "state": "Close NovaBook Air 14 performance · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Close NovaBook Air 14 performance · VIOLATION_OBSERVED",
      "title": "tiktok-music · AP-FM1-01"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "115__travelzoo__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "115__travelzoo__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/115__travelzoo__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:e3843e85dbb6d3eed1dcea77fa7f35792205eb693be14d3b16b737b235d768c0"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::115__travelzoo__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 24,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "travelzoo",
      "slug": "formal-24-travelzoo-ap-fm1-01-b752b3c7751a",
      "steps": [
        {
          "action": "Space",
          "facts": [
            {
              "label": "Site",
              "value": "travelzoo"
            },
            {
              "label": "Control",
              "value": "Clear filters"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/706e3e7c72b3b86310472da670a0d74b252151302ff2f6431106fc4b0ea7f4c7.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:706e3e7c72b3b86310472da670a0d74b252151302ff2f6431106fc4b0ea7f4c7",
          "label": "Counterexample",
          "state": "Clear filters · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Space · Clear filters · VIOLATION_OBSERVED",
      "title": "travelzoo · AP-FM1-01"
    },
    {
      "atomicId": "AP-M1-04",
      "attemptId": "119__twitter__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "119__twitter__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
        "resultPath": "evidence/results/119__twitter__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:2777d472d4b473f1cd600c14a255cd603db477c58b3efdc2b1151abd45d06ba4"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::119__twitter__g2-taxonomy-informed__120s__replay-1:AP-M1-04:first-counterexample",
      "order": 25,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "twitter",
      "slug": "formal-25-twitter-ap-m1-04-f2d3a821f0cf",
      "steps": [
        {
          "action": "Escape",
          "facts": [
            {
              "label": "Site",
              "value": "twitter"
            },
            {
              "label": "Control",
              "value": "active dialog"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/8d1dc139471164359319b2df1f11b7506f70a197a865dc4c5aedddbf35f14925.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:8d1dc139471164359319b2df1f11b7506f70a197a865dc4c5aedddbf35f14925",
          "label": "Counterexample",
          "state": "active dialog · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Escape · active dialog · VIOLATION_OBSERVED",
      "title": "twitter · AP-M1-04"
    },
    {
      "atomicId": "AP-FM1-01",
      "attemptId": "136__zocdoc__g2-taxonomy-informed__120s__replay-1",
      "evidence": {
        "occurrenceId": "136__zocdoc__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
        "resultPath": "evidence/results/136__zocdoc__g2-taxonomy-informed__120s__replay-1.json.gz",
        "resultSha256": "sha256:9bb4e6398b414ffa9b6a1188dd816d60cd76476229998ea532a7326af6219226"
      },
      "excludedFromClaims": false,
      "findingKind": "formal",
      "id": "F::136__zocdoc__g2-taxonomy-informed__120s__replay-1:AP-FM1-01:first-counterexample",
      "order": 26,
      "outcome": "VIOLATION_OBSERVED",
      "reason": "Checker counterexample; pending reviewer validation.",
      "siteId": "zocdoc",
      "slug": "formal-26-zocdoc-ap-fm1-01-a352f5e88ce7",
      "steps": [
        {
          "action": "Enter",
          "facts": [
            {
              "label": "Site",
              "value": "zocdoc"
            },
            {
              "label": "Control",
              "value": "Continue to your details"
            },
            {
              "label": "Outcome",
              "value": "VIOLATION_OBSERVED"
            }
          ],
          "focusBox": null,
          "id": "counterexample",
          "image": "assets/e19688cb112149d2b467c5ed983fb6e4b85d16aa0c3d206d26191939d6109e63.jpeg",
          "imageRole": "witness",
          "imageSha256": "sha256:e19688cb112149d2b467c5ed983fb6e4b85d16aa0c3d206d26191939d6109e63",
          "label": "Counterexample",
          "state": "Continue to your details · VIOLATION_OBSERVED"
        }
      ],
      "summary": "Enter · Continue to your details · VIOLATION_OBSERVED",
      "title": "zocdoc · AP-FM1-01"
    }
  ],
  "properties": [
    {
      "atomicId": "AP-FM1-01",
      "bombadilAssertion": "export const AP_FM1_01_LOCAL_CONTROL_INVALIDATION_RETAINS_EXPOSED_FOCUS =\n  always(() => fm1LocalInvalidationFocusContractHolds(fm1ActivationObservation.current));",
      "ltlFormula": "G(stable_local_activation(c) && invalidated(c) -> F_[0,500ms] concrete_exposed_focus)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/focus/ap-fm1-01.ts#L392",
      "title": "Local control invalidation retains concrete exposed focus"
    },
    {
      "atomicId": "AP-FM3-01",
      "bombadilAssertion": "export const AP_FM3_01_AUTHOR_INTERCEPTED_TAB_MAKES_DOM_FOCUS_PROGRESS =\n  always(() => fm3TabProgressContractHolds(fm3TabObservation.current));",
      "ltlFormula": "G(author_cancelled_tab(c) && alternative_simple_target -> F_[0,500ms] exact_dom_focus != c)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/focus/ap-fm3-01.ts#L433",
      "title": "Author-intercepted Tab makes DOM focus progress"
    },
    {
      "atomicId": "AP-M1-01",
      "bombadilAssertion": "export const AP_M1_01_VISIBLE_DIALOGS_HAVE_NAMES =\n  always(() => m1DialogNameContractHolds(m1DialogNameObservation.current));",
      "ltlFormula": "G(visible_dialog(d) -> has_programmatic_name(d))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/dialog/ap-m1-01.ts#L133",
      "title": "Every visible dialog has a programmatic name"
    },
    {
      "atomicId": "AP-M1-02",
      "bombadilAssertion": "export const AP_M1_02_VISIBLE_DIALOGS_HAVE_NAMED_KEYBOARD_ACTIONS =\n  always(() => m1DialogActionContractHolds(m1DialogActionObservation.current));",
      "ltlFormula": "G(visible_dialog(d) -> exists_named_sequential_focus_action(d))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/dialog/ap-m1-02.ts#L173",
      "title": "Every visible dialog exposes a named sequential-focus action"
    },
    {
      "atomicId": "AP-M1-03",
      "bombadilAssertion": "export const AP_M1_03_ESCAPE_CLOSES_EXACT_ACTIVE_DIALOG =\n  always(() => m1EscapeDialogContractHolds(m1EscapeDialogObservation.current));",
      "ltlFormula": "G(escape_in_visible_dialog(d) -> F_[0,500ms] !visible(d))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/dialog/ap-m1-03.ts#L176",
      "title": "Escape closes the exact active dialog"
    },
    {
      "atomicId": "AP-M1-04",
      "bombadilAssertion": "export const AP_M1_04_DIALOG_CLOSE_RESTORES_EXACT_INVOKER =\n  always(() => m1ExactInvokerReturnContractHolds(m1FocusReturnObservation.current));",
      "ltlFormula": "G(bound_modal_escape_closes(d,i) -> F_[0,500ms] focus_is_exact_invoker(i))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/dialog/ap-m1-04.ts#L263",
      "title": "Closing an exact modal restores its exact eligible invoker"
    },
    {
      "atomicId": "AP-M1-05",
      "bombadilAssertion": "export const AP_M1_05_NEW_EXACT_MODAL_RECEIVES_FOCUS =\n  always(() => m1NewModalFocusContractHolds(m1NewModalFocusObservation.current));",
      "ltlFormula": "G(trusted_activation_opens_exact_modal(d) -> F_[0,500ms] focus_inside(d))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/dialog/ap-m1-05.ts#L233",
      "title": "One newly opened exact modal receives focus"
    },
    {
      "atomicId": "AP-N1-01",
      "bombadilAssertion": "export const AP_N1_01_COMPLETED_VIEW_HAS_ORIENTATION_ANCHOR =\n  always(() => n1OrientationContractHolds(n1OrientationObservation.current));",
      "ltlFormula": "G(document_complete -> visible_orientation_anchor_count > 0)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/navigation/ap-n1-01.ts#L124",
      "title": "A completed view exposes a visible orientation anchor"
    },
    {
      "atomicId": "AP-N2-01",
      "bombadilAssertion": "export const AP_N2_01_LONG_PREFIX_HAS_EXACT_BYPASS =\n  always(() => n2BypassContractHolds(n2BypassObservation.current));",
      "ltlFormula": "G(long_keyboard_prefix -> exact_bypass_control_present)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/navigation/ap-n2-01.ts#L197",
      "title": "A long keyboard prefix exposes an exact bypass target"
    },
    {
      "atomicId": "AP-N2-02",
      "bombadilAssertion": "export const AP_N2_02_MAIN_BYPASS_ESTABLISHES_TARGET_CONTINUATION =\n  always(() => n2BypassReachContractHolds(n2BypassReachObservation.current));",
      "ltlFormula": "G(exact_main_bypass_enter(c,t) -> F_[0,500ms](focus_at_or_inside(t) OR requested_next_Tab && X_[0,100ms] exact_expected_continuation(t)))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/navigation/ap-n2-02.ts#L582",
      "title": "Exact main-content bypass establishes target continuation"
    },
    {
      "atomicId": "AP-PS1-01",
      "bombadilAssertion": "export const AP_PS1_01_TAB_SETTLES_OUTSIDE_HIDDEN_SUBTREES =\n  always(() => ps1ContractHolds(ps1TabObservation.current));",
      "ltlFormula": "G(settled_trusted_tab -> !settled_focus_programmatically_hidden)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/focus/ap-ps1-01.ts#L199",
      "title": "Trusted Tab settles outside programmatically hidden subtrees"
    },
    {
      "atomicId": "AP-S2-01",
      "bombadilAssertion": "export const AP_S2_01_EXPANDED_STATE_MATCHES_CONTROLLED_REGION =\n  always(() => s2ExpandedContractHolds(s2ExpandedObservation.current));",
      "ltlFormula": "G(expansion_action(c,r) -> F_[0,500ms] expanded(c)=visible(r))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/state/ap-s2-01.ts#L191",
      "title": "Expanded state matches the exact controlled region"
    },
    {
      "atomicId": "AP-S2-02",
      "bombadilAssertion": "export const AP_S2_02_ARIA_CHECKED_MATCHES_NATIVE_STATE =\n  always(() => s2CheckedContractHolds(s2CheckedObservation.current));",
      "ltlFormula": "G(native_checkable_with_aria(c) -> aria_checked(c)=native_checked(c))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/state/ap-s2-02.ts#L115",
      "title": "Redundant ARIA checked state matches native checked state"
    },
    {
      "atomicId": "AP-S2-03",
      "bombadilAssertion": "export const AP_S2_03_ARIA_SELECTED_MATCHES_NATIVE_OPTION =\n  always(() => s2SelectedContractHolds(s2SelectedObservation.current));",
      "ltlFormula": "G(native_option_with_aria(o) -> aria_selected(o)=native_selected(o))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/state/ap-s2-03.ts#L107",
      "title": "Redundant ARIA selected state matches native option state"
    },
    {
      "atomicId": "AP-S2-04",
      "bombadilAssertion": "export const AP_S2_04_ARIA_VALUE_MATCHES_NATIVE_RANGE =\n  always(() => s2ValueContractHolds(s2ValueObservation.current));",
      "ltlFormula": "G(native_range_with_aria(r) -> aria_valuenow(r)=native_value(r))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/state/ap-s2-04.ts#L115",
      "title": "Redundant ARIA numeric value matches native range value"
    },
    {
      "atomicId": "AP-W1-01",
      "bombadilAssertion": "export const AP_W1_01_MANAGED_COMBOBOX_HAS_VALID_ACTIVE_DESCENDANT =\n  always(() => w1ActiveDescendantContractHolds( w1ActiveDescendantObservation.current, ));",
      "ltlFormula": "G(expanded_managed_combobox(c) -> valid_active_descendant(c))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w1-01.ts#L179",
      "title": "An expanded managed combobox has a valid active descendant"
    },
    {
      "atomicId": "AP-W1-02",
      "bombadilAssertion": "export const AP_W1_02_ARROWS_MOVE_TO_ADJACENT_OPTION =\n  always(() => w1ArrowContractHolds(w1ArrowObservation.current));",
      "ltlFormula": "G(admitted_combobox_arrow(c,k,next) -> F_[0,500ms] active(c)=next)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w1-02.ts#L209",
      "title": "Combobox arrows move to the declared adjacent option"
    },
    {
      "atomicId": "AP-W1-03",
      "bombadilAssertion": "export const AP_W1_03_ENTER_COMMITS_EXACT_ACTIVE_OPTION =\n  always(() => w1CommitContractHolds(w1CommitObservation.current));",
      "ltlFormula": "G(enter_on_active_option(c,o) -> F_[0,500ms] committed(c,o))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w1-03.ts#L256",
      "title": "Enter commits the exact active combobox option"
    },
    {
      "atomicId": "AP-W2-01",
      "bombadilAssertion": "export const AP_W2_01_MANAGED_GRID_HAS_VALID_ACTIVE_CELL =\n  always(() => w2ActiveCellContractHolds(w2ActiveCellObservation.current));",
      "ltlFormula": "G(managed_grid(g) -> valid_active_cell(g))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w2-01.ts#L164",
      "title": "A managed grid has one exact owned active cell"
    },
    {
      "atomicId": "AP-W2-02",
      "bombadilAssertion": "export const AP_W2_02_ARROWS_MOVE_TO_ADJACENT_CELL =\n  always(() => w2ArrowContractHolds(w2ArrowObservation.current));",
      "ltlFormula": "G(admitted_grid_arrow(g,k,next) -> F_[0,500ms] active(g)=next)",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w2-02.ts#L226",
      "title": "Grid arrows move to the declared adjacent cell"
    },
    {
      "atomicId": "AP-W3-01",
      "bombadilAssertion": "export const AP_W3_01_ROLE_SPECIFIC_ACTIVATION_PRODUCES_EXACT_EFFECT =\n  always(() => w3ActivationResponseContractHolds( w3ActivationResponseObservation.current, ));",
      "ltlFormula": "G(admitted_role_activation(c,k,e) -> F_[0,500ms] exact_effect(e))",
      "sourceUrl": "https://github.com/Oscar-Ge/LTL-UI/blob/1bba7afd98e2d198911c2bdf48ea4213d2c3eaca/online-v2/specs/atomic/properties/widget/ap-w3-01.ts#L1106",
      "title": "Role-specific activation produces its exact browser effect"
    }
  ],
  "schemaVersion": "ltl-ui-g2-precision-data/2"
});
})();
